name: mongoose-plugin
description: Provide MongoDB access by Mongoose library
display-name: mongoose-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - javascript
  - mongoose
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Input MongoDB connection string
    type: text
    name: mongodb_connection_production
    default: mongodb://nome_banco:senha@servidor.com.br:27017/usuario
  # - label: Example of number
  #   type: int
  #   name: any_number
  #   default: "10"
  # - label: Example of list
  #   type: multiselect
  #   name: any_list
  #   items:
  #     - item1
  #     - item2

hooks:
  - type: run
    trigger: after-render
    commands:
      - npm install args-parser
      - npm install lodash
      - npm install mongoose
      - npm install mongoose-beautiful-unique-validation
      - npm install mongoose-paginate
      - npm install node-restful

  - type: edit-json
    trigger: after-render
    path: config/setup-registry.json
    indent: "\t"
    encoding: utf-8
    changes:
      - jsonpath: "$"
        update:
          value: |
            {
              "mongoose": "./config/mongoose"
            }
        when:
          not-exists: "$.mongoose"
      - jsonpath: "$.mongoose"
        update:
          value: |
            "./config/mongoose"